# Setup
title:               kkilme's playground
tagline:             Place for rest
description:         'Thanks for visiting my blog! Feel free to look around.'
url:                 https://kkilme.github.io/
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Seojin Jo
  url:               https://github.com/kkilme
  email:             jojo5142@naver.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
comment : 
  provider :         "disqus"
  disqus :
      shortname :    "kkil-blog"